name: Insatll apache2

on:
  push:

jobs:
  Install-Apache2:
    runs-on: ubuntu-latest

    steps:
    - name: update apache2
      run: sudo apt-get update

    - name: Install apache2
      run: sudo apt install apache2

    - name: start services
      run: sudo systemctl start apache2

    - name: veriify
      run: curl -I http://localhost
    
