name: Install apache2 

on: 
  push:

jobs:
    Installation-Apache2:
      runs-on: ubuntu-latest

      steps: 
      - name: update packeges
        run: sudo apt-get update 

      - name: Install Apache2
        run: sudo apt install -y apache2

      - name: start services
        run: sudo systemctl start apache2
 
    Install-nginx:
      runs-on: ubuntu-latest

      steps: 
      - name: update packages
        run: sudo apt-get update

      - name: Install nginx
        run: sudo apt install -y nginx
        
